parameters:
#    flyaround_map.example.class: Flyaround\MapBundle\Example

services:
    flyaround.map.admin.terrain:
        class: Flyaround\MapBundle\Admin\TerrainAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: places, label: Terrains }
        arguments: [null, Flyaround\MapBundle\Entity\Terrain, FlyaroundMapBundle:TerrainAdmin]

    flyaround.map.admin.fly:
            class: Flyaround\MapBundle\Admin\FlyAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: places, label: Flys }
            arguments: [null, Flyaround\MapBundle\Entity\Fly, FlyaroundMapBundle:FlyAdmin]

