<?php

namespace Flyaround\MapBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FlyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlyRepository extends EntityRepository
{
}
