flyaround_map:
    resource: "@FlyaroundMapBundle/Resources/config/routing.yml"
    prefix:   /

flyaround_core:
    resource: "@FlyaroundCoreBundle/Resources/config/routing.yml"
    prefix:   /terrain



fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

soanata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

homepage:
    pattern:  /
    defaults: { _controller: FlyaroundCoreBundle:Default:index }

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

ApplicationSonataUserBundle:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing.yml"
    prefix:   /

sonata_api_user:
    type:         rest
    prefix:       /api/user
    resource:     "@SonataUserBundle/Resources/config/routing/api.xml"
