fly:
    path:     /
    defaults: { _controller: "FlyaroundMapBundle:Fly:index" }

fly_show:
    path:     /{id}/show
    defaults: { _controller: "FlyaroundMapBundle:Fly:show" }

fly_new:
    path:     /new
    defaults: { _controller: "FlyaroundMapBundle:Fly:new" }

fly_create:
    path:     /create
    defaults: { _controller: "FlyaroundMapBundle:Fly:create" }
    requirements: { _method: post }

fly_edit:
    path:     /{id}/edit
    defaults: { _controller: "FlyaroundMapBundle:Fly:edit" }

fly_update:
    path:     /{id}/update
    defaults: { _controller: "FlyaroundMapBundle:Fly:update" }
    requirements: { _method: post|put }

fly_delete:
    path:     /{id}/delete
    defaults: { _controller: "FlyaroundMapBundle:Fly:delete" }
    requirements: { _method: post|delete }
